apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: docker.io/sunnypandas/accountinfo
      context: ../account-info
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
